### ISSUE TITLE
Create you first basic extension

### ISSUE THREAD

**Issue by TheAddictedOne** [TheAddictedOne/dailymotion-internship#1]
Before jumping into Player Webextension, it's good to start creating your own extension from scratch.
Mozilla has a great tutorial for it. Follow it to grasp the basics.

⚠️  **Recommendation**
I recommand to run the extension on Firefox: even if web extensions follow a standard API, there are some little differences between Chrome and Firefox (we can discuss about them).

- What is an extension? https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions
- Build your 1st extension: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

**Comment by Marie-Bewiwi** [comment]
Done ! I also turned the background of mozilla domain webpages in blue. I tried to create a text node but I think I need to update my knowledge in order to make it work !
