### ISSUE TITLE
Design mockups for player webextension options panel

### ISSUE THREAD

**Issue by TheAddictedOne** [TheAddictedOne/dailymotion-internship#4]
Our extension looks like this:
- [Current design](https://user-images.githubusercontent.com/2213825/104039744-0940eb00-51d7-11eb-898d-938412d70d58.png)

As you can see, some buttons are poorly designed (see "Additional QS" inputs), because we were focused on making it work.  
It's also not close to other tools:
- [Example of an internal tool](https://user-images.githubusercontent.com/2213825/104040308-c59ab100-51d7-11eb-9790-b23301ff0ebc.png)

A more problematic issue is the integration in some websites: as CSS properties collide with external websites, the extension feels broken sometimes:
- [Example with letribunaldunet.fr](https://user-images.githubusercontent.com/2213825/104040832-70ab6a80-51d8-11eb-9330-f69e6d9640bf.png)

The goal of this ticket is to move the modal design to the "options" panel, available natively in web extension.

**Comment by Marie-Bewiwi** [comment]
I still have to design what it would look like with every custom selected and some QS input ( according to Hine )
I also have to make it lighter, with much more padding and margin

**Comment by TheAddictedOne** [comment]
We had a look and reviewed it this afternoon. All good to me 👍 . Can you please share a screenshot of your work in this ticket? Thx 🙏

**Comment by Marie-Bewiwi** [comment]
- State 1 : no redirect, no logger, no QS
![image](https://user-images.githubusercontent.com/63472078/105041076-d8787580-5a62-11eb-81a2-96a7ac6bdb11.png)

- State 2 : custom environment, custom logger and Add QS clicked.
![image](https://user-images.githubusercontent.com/63472078/105041185-f7770780-5a62-11eb-8716-8a4ddb81be11.png)
